### ISSUE TITLE
Implement Rank Filter for Top-5 Summary Section

### ISSUE THREAD

**Issue by porkchop520** [Moncleared/open-dkp-client#1]
Currently on the summary page, the top section shows Top-5 DKP for each class across all ranks.

Requesting a feature that would allow administrators the ability to choose which ranks show up on the Top-5 DKP per class section.

For example, we have the following ranks:
- Leader
- Officer
- Member
- Recruit
- Box
- Friends and Family

We **only** want Leader, Officer, Member, and Recruit to show up on the Top-5 DKP section.

**Comment by Moncleared** [comment]
Completed this, will merge shortly

**Comment by Moncleared** [comment]
Resolved with 4f23477badb3dd7b7a56d2cce29cea17de060e54

Leveraging the existing Settings API, simply created a small panel in the Admin page for controlling which Ranks are eligible. Updated the Summary Page to read this new setting if it exists and apply the filtering appropriately
