### ISSUE TITLE
Implement Identification of Inactive Characters on Characters Screen

### ISSUE THREAD

**Issue by porkchop520** [Moncleared/open-dkp-client#4]
On the 'Characters' screen, the only indicator to determine if a character is inactive is to check the 'Include Inactives?' and open each character individually.

It would be helpful if there was an identifier to show whether a character is currently Active or Inactive from the Characters table that would also be able to sort or filter on. Enhancement would make it easier to audit the inactive character list.

**Comment by Moncleared** [comment]
Merging this update tonight, you'll have a new column on the Characters list page that displays Active or Inactive plus the ability to sort and filter based on the column

**Comment by Moncleared** [comment]
Resolved with 364f4eead4fe8138ed618ad5e63e7f055df9bd93
